refactor: playing status
shuyangzhang/Kyouka pull request #16
Opened 2022-06-28 14:57 UTC by omoidesu

update playing status at create_container and stop_container method

2022-06-28 15:08 UTC, shuyangzhang requested changes

2022-06-28 15:08 UTC, shuyangzhang commented on app/voice_utils/container_handler.py
> +
我觉得这个函数出现在 container_handler 里有点奇怪，应该在其他地方，仅仅在这里被调用

2022-06-28 15:08 UTC, shuyangzhang commented on app/bot.py
> +bot = Bot(token=settings.token)
我还是觉得bot作为参数传入比较好，单独一个文件的话，后续还是有可能出现循环依赖的问题

2022-06-28 15:11 UTC, omoidesu commented on app/bot.py
> +bot = Bot(token=settings.token)
就是出现了循环依赖的问题我才单独拿出来的

main.py
```python
from app.voice_utils.container_handler import create_container, stop_container, pause_container, unpause_container
```

container_handler.py
```python
from app.main import bot
```

2022-06-28 15:14 UTC, omoidesu commented on app/voice_utils/container_handler.py
> +
这个函数我也不知道放在哪里比较合适，因为只有在这里调用就直接放到这了

2022-06-28 15:17 UTC, shuyangzhang commented on app/bot.py
> +bot = Bot(token=settings.token)
明白，我看到你这个设计就知道是为了防止循环依赖，我的意思是，当具体的逻辑需要依赖bot或者ctx的时候，传入参数是从根本上解决循坏依赖的方法，拿出来仅仅是一个trick，未来仍然有可能出现循环依赖的问题

2022-06-28 15:52 UTC, omoidesu commented on app/voice_utils/container_handler.py
> +
看板如果继续用定时任务确实可以加个cache，然后这样从3分钟减少一点

2022-07-29 16:23 UTC, shuyangzhang commented
由于目前kook的在玩状态存在一定的延迟，如果按照此方法改后，bot的在玩状态仍然是无法正确地反映bot实际的繁忙状态，因此暂时先将此PR关闭了，未来kook官方如果有改动，再考虑此方面的修改。

2022-07-29 16:23 UTC, closed without merging

2022-07-29 16:23 UTC, Hinanawimoko commented
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。